config/samples/metallb.yaml

Add metallb helmchartproxy sample
Fixes #

Create metallb helmchartproxy example

---

api/v1alpha1/helmchartproxy_webhook.go
api/v1alpha1/helmreleaseproxy_webhook.go
config/crd/bases/addons.cluster.x-k8s.io_helmchartproxies.yaml
config/rbac/role.yaml
config/webhook/manifests.yaml
controllers/helmchartproxy/helmchartproxy_controller.go
controllers/helmreleaseproxy/helmreleaseproxy_controller.go
hack/verify-shellcheck.sh
scripts/ci-test.sh

Change empty label selector to select all clusters, fix manifest, verify, and test

---

Makefile
cloudbuild.yaml

**What this PR does / why we need it**: Adds a cloudbuild.yaml file so we can run image publishing jobs.
Fixes #

🌱 Add cloudbuild.yaml for prow job

---

Makefile
config/default/manager_image_patch.yaml
hack/get-project-maintainers.sh

:seedling: Fix incorrect references in Makefile and project maintainer script

---

config/samples/cloud-provider-azure.yaml

Updates the cloud provider azure to latest available version (that one is ~1 year old).

:seedling: Update cloud-provider-azure sample version

---

Makefile
hack/get-project-maintainers.sh

… version
**What this PR does / why we need it**: Fix alias in ./hack/get-project-maintainers.sh script and bump kpromo version 
Fixes #

:seedling: Fix alias in ./hack/get-project-maintainers.sh script and bump kpromo version

---

controllers/helmchartproxy/helmchartproxy_controller.go
controllers/helmchartproxy/helmchartproxy_controller_phases.go
controllers/helmchartproxy/suite_test.go
controllers/helmreleaseproxy/helmreleaseproxy_controller.go
controllers/helmreleaseproxy/suite_test.go
go.mod
internal/helm_operations.go
internal/value_substitutions.go
main.go

**What this PR does / why we need it**: Rename module to sigs.k8s.io/cluster-api-addon-provider-helm so we can import it successfully in other projects.
Fixes #

🌱 Rename module to sigs.k8s.io/cluster-api-addon-provider-helm

---

Makefile
config/samples/cloud-provider-azure.yaml

**What this PR does / why we need it**: Fix make target for release note generation
Fixes #

🐛 Fix make target for release note generation

---

Makefile

:bug: Fix follow up bug with release notes make target

---

.github/workflows/release.yml

🐛 Fix release draft GitHub action

---

controllers/helmchartproxy/helmchartproxy_controller.go

!-- please add an icon to the title of this PR (see https://sigs.k8s.io/cluster-api/CONTRIBUTING.md#contributing-a-patch), and delete this line and similar ones -->
**What this PR does / why we need it**: Adds a watch on Clusters such that we trigger reconciliation on HelmChartProxies that would select it. Before, if a new Cluster was created, we'd have to wait the 10 min reconciliation period before the HelmChartProxy would requeue and able to select the cluster.
Fixes #

✨ Add watch to HelmChartProxy for Cluster creation and updates

---

controllers/helmchartproxy/helmchartproxy_controller.go

Currently, the `matchLabels` field in the label selector is supported. Add support for the `matchExpressions` field.
supplementary information:
If the label selector isn't defined, it matches all workload clusters by default. I think this behavior is acceptable, so the key and value validation mentioned in [this comment](https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/blob/0ccbfd10df6266dc66459f09f8d6fe017e65ef0a/controllers/helmchartproxy/helmchartproxy_controller.go#L252) is unnecessary.
Fixes #15

:sparkles:Add support for the matchExpressions field in the label selector

---

config/samples/cloud-provider-azure.yaml

🌱 Use string join function in cloud provider azure chart

---

Makefile

**What this PR does / why we need it**: Change the output file of `make release-manifests` to `addon-components.yaml` so it will be compatible with the [clusterctl PR](https://github.com/kubernetes-sigs/cluster-api/pull/8472) to support CAAPH.
Fixes #

🌱 Rename 'add-on-components.yaml' to 'addon-components.yaml' in make target

---

internal/helm_operations.go

🐛 Fix nil pointer bug in Helm uninstall

---

controllers/helmchartproxy/helmchartproxy_controller_phases.go
controllers/helmchartproxy/helmchartproxy_controller_phases_test.go
controllers/helmchartproxy/helmchartproxy_controller_test.go
controllers/helmchartproxy/suite_test.go

**What this PR does / why we need it**: Add controller tests for `helmchartproxy_controller.go` and `helmchartproxy_controller_phases.go`.
Fixes #

✨ Add controller tests for HelmChartProxy

---

docs/quick-start.md

**What this PR does / why we need it**: Update installation steps in quick start to use `clusterctl init --addon helm`
Fixes #

📖  Update quick-start.md to include installation steps using clusterctl

---

main.go

**What this PR does / why we need it**: Set default log level to 2
Fixes #

🌱 Set default log level to 2

---

.github/workflows/golangci-lint.yml
.golangci.yaml
Makefile
api/v1alpha1/groupversion_info.go
api/v1alpha1/helmchartproxy_types.go
api/v1alpha1/helmchartproxy_webhook.go
api/v1alpha1/helmreleaseproxy_types.go
api/v1alpha1/helmreleaseproxy_webhook.go
api/v1alpha1/webhook_suite_test.go
config/crd/bases/addons.cluster.x-k8s.io_helmchartproxies.yaml
config/crd/bases/addons.cluster.x-k8s.io_helmreleaseproxies.yaml
controllers/helmchartproxy/helmchartproxy_controller.go
controllers/helmchartproxy/helmchartproxy_controller_phases.go
controllers/helmchartproxy/helmchartproxy_controller_phases_test.go
controllers/helmchartproxy/helmchartproxy_controller_test.go
controllers/helmchartproxy/suite_test.go
controllers/helmreleaseproxy/helmreleaseproxy_controller.go
controllers/helmreleaseproxy/helmreleaseproxy_controller_test.go
controllers/helmreleaseproxy/suite_test.go
internal/helm_client.go
internal/kubeconfig.go
internal/value_substitutions.go
main.go

Right now, we're running just a few of the linters available by default in golangci. This PR enables additional linters that will improve the quality of the code.
Fixes #

🌱 Implement advanced linting

---

controllers/helmreleaseproxy/helmreleaseproxy_controller.go

**What this PR does / why we need it**: Wait for control plane to be initialized in HelmReleaseProxy controller. The `ClusterAvailableCondition` will be set to false with `WaitingForControlPlaneAvailableReason` if the `ControlPlaneInitializedCondition` is not true. This avoids having to fail on `GetClusterKubeconfig` or trying to reach the API server.
Fixes #

✨ Wait for control plane to be initialized in HelmReleaseProxy controller

---

OWNERS_ALIASES

**What this PR does / why we need it**: Welcome @mboersma to becoming a reviewer!

🌱 Add Matt Boersma to reviewers

---

test/e2e/common.go
test/e2e/helm_install.go
test/e2e/helm_test.go
test/e2e/helm_upgrade.go

🌱 Add e2e test to install Helm chart on multiple Clusters

---

metadata.yaml
test/e2e/config/helm.yaml
test/e2e/data/shared/v1beta1-provider/metadata.yaml

**What this PR does / why we need it**: Fix missing minor version in metadata.yaml
Fixes #

🐛 Fix missing minor version in metadata.yaml

---

config/crd/patches/visualizer_label_in_helmchartproxies.yaml
config/crd/patches/visualizer_label_in_helmreleaseproxies.yaml

✨ Add visualizer label patch for HelmChartProxy and HelmReleaseProxy

---

test/e2e/config/helm.yaml

🌱 Bump CAAPH version in API version upgrade test

---

config/crd/kustomization.yaml

**What this PR does / why we need it**: Missing section in kustomization.yaml to include the patches.
Fixes #

🐛 Add visualizer label patch to kustomization.yaml

---

metadata.yaml

🐛 Remove extra key in metadata.yaml

---

.github/workflows/yamlvalidator.yml
.github/yamllint_config.yaml

This gives us basic protection against invalid YAML from landing in the project. we can configure which types of checks we want to include and which checks should be set as warning.
Fixes #218

✨ Add yaml CI validation for yml\yaml files

---

Makefile

**What this PR does / why we need it**: Instead of throwing an error, this will default it to use the local kind registry like in CAPZ.
Fixes #186

🌱 Set REGISTRY to localhost:5000 by default if gcloud project name is not set

---

controllers/controllers_test.go
controllers/helmchartproxy/helmchartproxy_controller.go
controllers/suite_test.go

This PR fixes unexpected removal of the HelmChartProxy finalizer and itself in case the Helm release cannot be uninstalled. 
Fixes #315

🐛 HelmChartProxy is removed even when the release cannot be uninstalled

---

test/e2e/config/helm.yaml
test/e2e/data/shared/v1beta1-provider/metadata.yaml

🐛 Update API version upgrade test for CAAPH v0.3

---

.github/workflows/golangci-lint.yml
.golangci.yaml
controllers/helmchartproxy/helmchartproxy_controller_phases_test.go
controllers/helmchartproxy/helmchartproxy_controller_test.go
controllers/helmreleaseproxy/helmreleaseproxy_controller_test.go

:seedling: Fix bump golangci/golangci-lint-action from 6.3.1 to 6.5.0

---

docs/development.md

:seedling: Fix typos in development guide

---

metadata.yaml
test/e2e/data/shared/v1beta1-provider/metadata.yaml

This fixed missing Metadata kind in metadata.yaml files
Fixes #

:seedling: Fix missing Metadata kind in metadata.yaml

---

main.go

Adds two command line arguments: `--kube-api-qps` and `--kube-api-burst` which configures manager's kube api client's client side throttling.
This is done in the similar fashion as in cluster-api repo: https://github.com/kubernetes-sigs/cluster-api/blob/main/main.go#L230-L234
Besides those two parameters, UserAgent and WarningHandler also configured the same way as in cluster-api: https://github.com/kubernetes-sigs/cluster-api/blob/main/main.go#L288-L292

🌱 Add rest config options (kube-api-qps & kube-api-burst)
