- internal/helm_operations.go
**What this PR does / why we need it**: If we have an error from getting a Helm release and it's not an `ErrReleaseNotFound`, return the error to requeue. Before, we were assuming that the error must be an `ErrReleaseNotFound`.
Fixes #19
> Fix nil pointer issue when trying to check if a Helm release exists

- docs/quick-start.md
Nit fix while going through the quick-start. Change the repo url to the new location under kuberentes-sigs
> :book: DOCS: Fix remote repo url

- config/samples/calico-cni.yaml
- docs/development.md
- hack/setup-calico-autoinstallation.sh
If CNI is not installed, the sample HelmChartProxy of nginx-ingress will not work, so I want to install CNI automatically.
Registering HelmChartProxy of calico as a Tilt resource, developers will no longer have to worry about CNI.
Additions and modifications
- `develop.md`: Add a calico auto-install configuration to the development docs.
- `calico-cni.yaml`: Modify a HelmChartProxy manifest of calico to target all workload clusters.
- `setup-calico-autoinstallation.sh`: Create a shell script to register HelmChartProxy manifest of calico as a Tilt resource.
Fixes #8
> Automatic installation of Calico on workload clusters

- main.go
Add flags to the manager to be able to set various leader election configurations. These leader-election flags are supported by the [manager](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Options). Moreover most projects in the cluster-api umbrella already support them.
Fixes #34
> :sparkles: Add leader election lease related flags

- Makefile
- config/default/kustomization.yaml
- config/default/kustomizeconfig.yaml
- config/default/manager_image_patch.yaml
- config/default/manager_pull_policy.yaml
- config/samples/metallb.yaml
- hack/verify-container-images.sh
- hack/version.sh
- scripts/ci-e2e-lib.sh
**What this PR does / why we need it**: Fix registry URL, image name, and job scripts which removed references to CAPI images.
Fixes #
> :seedling: Fix registry URL, image name, and job scripts

- Makefile
- config/default/kustomization.yaml
- config/manager/kustomization.yaml
- metadata.yaml
- tilt-provider.yaml
**What this PR does / why we need it**: Adds make targets to install, uninstall, deploy, and undeploy to a kind cluster. Also removes references to the Docker repo `jont828` and replaces it with the gcr staging repo.
Fixes #
> 🌱 Add deployment make target and files for GitHub release actions

- api/v1alpha1/condition_consts.go
- controllers/helmreleaseproxy/helmreleaseproxy_controller.go
- internal/helm_operations.go
**What this PR does / why we need it**: Fix a bug where the HelmReleaseProxy ready condition was set to true if a release was present regardless of if it was in a failed state. Now, the controller will attempt to reupgrade the failed release and return an error if it failed. This allows us to retry on a failed release with exponential backoff. The `GenerationChangedPredicate` was also added to the HelmReleaseProxy event filter to ignore updates to the metadata and status, since otherwise we would infinitely requeue as the `status.revision` field is always incremented.
Fixes #16
> 🐛 Retry upgrades on failed releases and fix status and requeue bug

- controllers/helmreleaseproxy/helmreleaseproxy_controller.go
**What this PR does / why we need it**: Adds an event filter for HelmReleaseProxy to make it consistent with HelmChartProxy. This will allow reconciliation to be paused when the pause annotation is applied.
Fixes #
> ✨ Add event filter for HelmReleaseProxy when it is paused

- hack/version.sh
- main.go
- version/version.go
**What this PR does / why we need it**: Adds the `version` package with loads the fields from `ldflags` into the controller. Also fixes a bug in `version.sh` where it referred to CAPI instead of CAAPH.
Fixes #
> ✨ Add git version info to controller

- Makefile
- config/crd/kustomization.yaml
- config/crd/patches/clusterctl_move_label_in_helmchartproxies.yaml
- controllers/helmchartproxy/helmchartproxy_controller.go
**What this PR does / why we need it**: Have the HelmChartProxy controller set the ClusterctlMoveHierarchyLabel on HelmChartProxies so that it will be discovered by `clusterctl move`.
Fixes #103
> 🌱 Set ClusterctlMoveHierarchyLabel on HelmChartProxy in CRD definition

- api/v1alpha1/helmchartproxy_webhook.go
- controllers/helmchartproxy/helmchartproxy_controller_phases.go
- controllers/helmreleaseproxy/helmreleaseproxy_controller.go
- controllers/helmreleaseproxy/helmreleaseproxy_controller_test.go
- internal/helm_client.go
- main.go
**What this PR does / why we need it**: Fixes a bug in #136 where a nil pointer exception was occurring in constructing the HelmReleaseProxy if Helm options was left blank.
Fixes #
> 🐛 Fix nil pointer bug in EnableClientCache option

- Makefile
- scripts/ci-e2e.sh
**What this PR does / why we need it**: Fix bug where `make docker-push` fails when registry is not set.
Fixes #
> 🐛 Use local kind registry by default in e2e tests

- .github/workflows/dependabot.yml
- .github/workflows/release.yml
- .github/workflows/scan.yml
Updates the Go version to v1.21 in GitHub actions that reference that, so it agrees with the version in go.mod. This fixes at least the dependabot/build action that is currently broken.
N/A
> 🐛 Bump Go version to v1.21 in GitHub actions

- Makefile
- test/e2e/data/addons-helm/v1beta1/bases/calico.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/e2e_suite_vars.go
Addresses minor cleanup comments made here: https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/pull/147#pullrequestreview-1852597431
N/A
> 🌱 Minor cleanup for e2e tests

- Makefile
- test/e2e/capi_test.go
- test/e2e/config/helm.yaml
- test/e2e/data/addons-helm/v1beta1/bases/cluster-with-topology.yaml
- test/e2e/data/addons-helm/v1beta1/cluster-template-upgrades.yaml
- test/e2e/data/addons-helm/v1beta1/cluster-template-upgrades/kustomization.yaml
- test/e2e/data/addons-helm/v1beta1/cluster-template.yaml
- test/e2e/data/addons-helm/v1beta1/clusterclass-quick-start.yaml
- test/e2e/data/kubetest/conformance.yaml
**What this PR does / why we need it**: Add e2e test and template for K8s version upgrade to verify that version upgrade works.
Fixes #
> ✨ Add e2e test and template for K8s version upgrade

- OWNERS
- OWNERS_ALIASES
- SECURITY_CONTACTS
Moves @CecileRobertMichon to emeritus approvers on CAAPH 🖖🏻, and syncs up the OWNERS files with CAPZ/CAPI.
N/A, but should stop PRs from being assigned to inactive maintainers (after other k8s clerical PRs are created...).
I'm 99% sure this is what she intended, but please LMK if I'm wrong.
> 🌱 Move CecileRobertMichon to emeritus approvers

- test/e2e/common.go
- test/e2e/helm_install.go
- test/e2e/helm_test.go
- test/e2e/helm_upgrade.go
- test/e2e/helpers.go
**What this PR does / why we need it**: Adds an additional spec to update a HelmChartProxy and verify that the revision and values have successfully changed.
Fixes #172
> ✨ Add e2e test spec to upgrade or reinstall a Helm chart on a Cluster

- controllers/helmchartproxy/helmchartproxy_controller_phases.go
HelmReleaseProxy should be created when there is a HelmChartProxy / Cluster with the same name in a different namespace
Fixes #176
> :bug: Add namespace when listing HelmReleaseProxies related to HelmChartProxy

- controllers/helmchartproxy/helmchartproxy_controller_phases.go
- controllers/helmchartproxy/helmchartproxy_controller_phases_test.go
- controllers/helmchartproxy/helmchartproxy_controller_test.go
This fixes a bug leading to duplicate `HelmReleaseProxy` resources
following a `clusterctl move` that can happen due to a race between
reconciling the `HelmChartProxy` and moving and unpausing the `Cluster`.
Fixes #188.
> :bug: Skip HelmChartProxy reconciliation for paused clusters

- test/e2e/config/helm.yaml
Updates the versions of CAPI in the e2e test configuration to the latest patches available.
None, but see #191 and #193
> 🌱 Bump CAPI versions in e2e config

- controllers/suite_test.go
Replaces the deprecated call to [`klogr.NewWithOptions()`](https://pkg.go.dev/k8s.io/klog/v2/klogr#pkg-functions) with the recommended API `textlogger.NewLogger`.
This deprecation has been failing the linter in PR #180, but curiously, no where else that I've seen. Regardless, it is an actual deprecation.
```
Running [/home/runner/golangci-lint-1.54.1-linux-amd64/golangci-lint run --out-format=github-actions --timeout=5m] in [] ...
Error: SA1019: klogr.NewWithOptions is deprecated: FormatSerialize is out-dated. For FormatKlog, use textlogger.NewLogger instead.  (staticcheck)
```
See #180
> 🌱 Replace deprecated call to klogr.NewWithOptions

- docs/releasing.md
Adds documentation to help maintainers do CAAPH product releases.
Fixes #198
> 📖 Add release process documentation

- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
This PR adds explicit security context best practices to the Deployment/pods for CAAPH. values have been taken from the [Cluster API Controller deployment](https://github.com/kubernetes-sigs/cluster-api/blob/main/config/manager/manager.yaml#L57-L64) securityContexts
Fixes #
> 🌱 add explicit securityContext the CAAPH deployment

- controllers/helmchartproxy/helmchartproxy_controller_phases_test.go
Fixes the `TestReconcileForCluster` intermittent failure by not re-using a test artifact after it has conditions added to it. It's not ideal that we mutate some of these test resources, but I'm avoiding a larger refactor here to get the tests passing reliably.
Fixes #220 
Thanks to @dmvolod for pointing out that `go test -count=2 ./controllers/helmchartproxy/...` makes this bug occur all the time. This allowed me to debug it. (Removing `t.Parallel()` also triggers the failure.)
> 🐛 Fix TestReconcileForCluster unit test

- go.mod
- go.sum
- test/e2e/config/helm.yaml
Updates CAPI to [v1.7.2](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.7.2) and all that entails. Also bumps the old version used in the `clusterctl` upgrade test to v1.6.5.
N/A
/kind cleanup
> 🌱 Bump CAPI to v1.7.2

- go.mod
- main.go
Adds logOptions from k8s.io/component-base/logs to streamline logging experience with other cluster-api providers, such as core/bootstrap/control-plane.
Adds ability to change logging format to JSON via `--logging-format=json` command line arg.
> :seedling: Add log options from k8s.io/component-base/logs

- internal/helm_client.go
This commit fixes the logic deciding to create a TLS client for OCI
charts.
The existing code was creating a non-TLS configured client if either the CA file
was unspecified or if `insecureSkipTLSVerify` was set to false. If a CA
file was specified then `insecureSkipTLSVerify` is always false, which meant
that a non-TLS client was always created, causing cert validation
failures if the OCI registry is served over TLS.
This commit changes the logic to create a non-TLS configured client if
both CA file is unset AND `insecureSkipTLSVerify` is false.
> :bug: Fix OCI client configuration logic

- controllers/helmchartproxy/helmchartproxy_controller_phases.go
- controllers/helmchartproxy/helmchartproxy_controller_phases_test.go
- controllers/helmreleaseproxy/helmreleaseproxy_controller.go
- controllers/helmreleaseproxy/helmreleaseproxy_controller_test.go
This PR fixes a nil pointer panic if a user does not specify CASecretRef in TLSConfig.
```
I0603 14:53:15.290968       1 controller.go:115] "Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller="helmchartproxy" controllerGroup="addons.cluster.x-k8s.io" controllerKind="HelmChartProxy" HelmChartProxy="default/```" namespace="default" name="node-feature-discovery-docker-cluster-cilium-helm-addon5" reconcileID="8498516d-cf78-49bb-bf2a-0ee6b355f62e"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x20d81cd]
goroutine 268 [running]: …
> :bug:  pointer checks if user doesn't specify CASecret

- Makefile
**What type of PR is this?**
/kind cleanup
Updates `setup-envtest` to a commit on `main` that fetches `envtest` binaries from the GitHub release on the [controller-tools](https://github.com/kubernetes-sigs/controller-tools) repo. This is to move away from using GCP resource buckets.
Fixes #250
See also:
- kubernetes-sigs/cluster-api#10569
- kubernetes-sigs/controller-runtime#2811
- kubernetes/k8s.io#2647
> 🌱 Use envtest binaries from controller-tools repo

- go.mod
- go.sum
- test/e2e/config/helm.yaml
Updates CAPI to [v1.7.4](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.7.4) and all that entails. Also bumps the old version used in the `clusterctl` upgrade test to v1.6.7.
N/A, but see #260 for prior art.
/kind cleanup
> 🌱 Bump CAPI to v1.7.4 

- api/v1alpha1/helmchartproxy_types.go
- config/crd/bases/addons.cluster.x-k8s.io_helmchartproxies.yaml
- config/crd/bases/addons.cluster.x-k8s.io_helmreleaseproxies.yaml
- internal/helm_client.go
expose the Helm upgrade resetThenReuseValues options in CAAPH
> :sparkles: expose resetThenReuseValues upgrade option

- .github/workflows/golangci-lint.yml
- controllers/helmchartproxy/helmchartproxy_controller.go
- controllers/helmchartproxy/helmchartproxy_controller_phases.go
- controllers/helmreleaseproxy/helmreleaseproxy_controller.go
- Bumped golangci-lint to v1.61.0 to ensure compatibility with recent code updates and improve linting accuracy.
- Addressed the following linting issues:
- S1009: Removed unnecessary nil check (gosimple).
- Printf: Resolved govet error by handling a non-constant format string in function call.
**What this PR does / why we need it**: This PR updates golangci-lint to the latest compatible version and resolves existing linting errors that were affecting pull requests. By addressing these issues, we maintain code quality and ensure smooth CI checks.
Fixes #300
> ✨ Update golangci-lint version and fix related linting issues

- Makefile
- api/v1alpha1/helmchartproxy_types.go
- api/v1alpha1/helmchartproxy_webhook.go
- api/v1alpha1/helmreleaseproxy_types.go
- api/v1alpha1/helmreleaseproxy_webhook.go
- config/crd/bases/addons.cluster.x-k8s.io_helmchartproxies.yaml
- config/crd/bases/addons.cluster.x-k8s.io_helmreleaseproxies.yaml
- config/manager/manager.yaml
- controllers/helmchartproxy/helmchartproxy_controller.go
- controllers/helmchartproxy/helmchartproxy_controller_phases.go
- controllers/helmchartproxy/helmchartproxy_controller_phases_test.go
- controllers/helmchartproxy/helmchartproxy_controller_test.go
- controllers/helmreleaseproxy/helmreleaseproxy_controller.go
- controllers/helmreleaseproxy/helmreleaseproxy_controller_test.go
- internal/util.go
- test/e2e/common.go
- test/e2e/config/helm.yaml
- test/e2e/helm_out_of_band.go
- test/e2e/helm_test.go
- test/e2e/helm_unchanged.go
- test/e2e/helpers.go
**What this PR does / why we need it**: Introduces a field called `ReconcileStrategy` which allows the user to specify if reconciliation will be continuous (as usual) or if the Helm chart should be successfully installed and no longer reconciled. This is intended as a "fire-and-forget" mode where users intend to hand off their Helm chart to GitOps or to make out of band changes.
Fixes #65
> ✨ Add `ReconcileStrategy` field to support continuous reconciliation or installing the Helm chart once

- config/manager/manager.yaml
This fix allows you to run a container with an operator on platforms that do not allow writing data to the root directory, such as OpenShift. 
The approach used is very simple, we mount /xdg as an emptyDir volume and redirect XDG_* variables used by helm there. This should work for upstream Kubernetes as well, but e2e validation is required.
Fixes #236
> :sparkles: Able to run controller inside the container platform with write access to root restrictions

- controllers/helmchartproxy/helmchartproxy_controller_phases.go
This PR introduces a feature to skip reconciliation when a cluster is in the process of being deleted. By checking the `DeletionTimestamp` of the cluster, the controller avoids creating or updating `HelmReleaseProxy` resources, ensuring a clean and efficient cluster teardown without unnecessary operations or potential errors.
Fixes https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/issues/319#issuecomment-2549275461
> ✨ Skip reconciliation if deleting cluster

- Dockerfile
- Makefile
This fix allows to customize docker build with Makefile parameters
Fixes #329
> :sparkles: Able to build provider docker without Makefile and Dockerfile modifications

- Makefile
This is fix for bug introduced in #340. CI job `post-cluster-api-addon-provider-helm-push-images` is utilizing BusyBox v1.35.0 (2022-08-01 15:14:44 UTC) multi-call binary set, which has number of limitations for grep, awk, etc. utilities.
This fix should work for regular OS as well for CI busybox.
Fixes #
> 🐛 Fix golang version getter bash script in Makefile

- metadata.yaml
This PR updates the `metadata.yaml` file in order to avoid issues when using `clusterctl`.
For example:
```
$ clusterctl generate provider --addon helm:v0.3.0
Error: invalid provider metadata: version v0.3.0 for the provider helm does not match any release series
```
> :bug: Update metadata for v0.3.0 release

- docs/quick-start.md
Update the quick-start docs with correct secret structure (the current one is outdated and is misleading users)
> 📖docs: Update quick-start.md with correct secret structure

- Makefile
This is small fix to support replace in go.mod while getting module version
Fixes #
> :bug: get_go_version in Makefile is not supporting replace in go.mod

- go.mod
- hack/tools/go.mod
- hack/tools/go.sum
Updates the golang tools to v1.23.10, which is a prerequisite for CAPI v1.10 and seems to be needed for dependabot lately as well.
Refs #386
> 🌱 Bump go compiler to v1.23.10

- Makefile
There was a bug in the Makefile that effectively made `make promote-images` fail with a https:// git remote to kubernetes/k8s,io.
> 🌱 Fix USER_FORK definition in Makefile

- metadata.yaml
**What this PR does / why we need it**: With the 0.4.0 release yesterday, the add-on is having issues installing for the latest version since the metadata.yaml wasn't updated for the new minor version:
```
capi-control… │ Fetching providers
capi-control… │ Error: invalid provider metadata: version v0.4.0 for the provider caaph-system/addon-helm does not match any release series. Available series: [0.1, 0.2, 0.3]. This usually means the release tag lacks an updated metadata.yaml or the repository URL is stale.
```
Fixes #
> :bug: add 0.4 for metadata.yaml
